version: '2'
services:
  app:
    restart: always
    build: ./prestonlloyd.com
    volumes:
    - ./prestonlloyd.com:/opt/prestonlloyd
    ports:
    - "3000:3000"
    depends_on:
    - redis
  redis:
    image: redis
