version: '2'
services:
  app:
    build: ./prestonlloyd.com
    env_file: .env
    volumes:
    - ./prestonlloyd.com:/opt/prestonlloyd
    expose:
    - '3000'
    command: 'node /opt/prestonlloyd/app.js'

  nginx:
    build: ./nginx
    volumes:
    - ./prestonlloyd.com/static:/www/static
    ports:
    - 3000:80
    links:
    - app:app
